# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9da2efde10e7ed50f6f85aeea165f4830a52355cd5e6089289676391e81b4badbede46904cf397253f44af9efd0c81b5355bda689c8e83fcf961f438129d98e0

test:
  secret_key_base: 75f570cbad84532e578b56cd686eee2030cec3076028c21aad8e62dc5fd04d75aa9616f5bc9a52d45e49ed3eb4349f0e70c07f673f4bb22e0d34a519f8a98523

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
